apiVersion: v1
kind: Service
metadata:
  name: analysticservice
  namespace: getrand
  labels:
    service: analysticservice
spec:
  selector:
    service: analysticservice
  ports:
    - port: 5004
      targetPort: 5004
  type: ClusterIP
